version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - jrolfs
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - jrolfs
    schedule:
      interval: daily
